### ISSUE TITLE
Updates to git commits

### ISSUE THREAD

**Issue by FuadBalashov** [ben-edgar/meme-creator#1]
closeMemeModal -> closeMemeEditor
turn let in our first commit to const
add placeholder text to the meme editor textInputs
Have the keyboard close function the app from the getgo
See if we can remove the View that wraps our image OR have it in the first commit.
Have the proptypes in the first commit, or remove them completely

**Comment by ben-edgar** [comment]
We can get rid of the style in the view wrapping the image, but we need the view to use it as a ref to take the screenshot! Also we need to keep collapsable or else the app crashes when you try to save it to the gallery.

**Comment by ben-edgar** [comment]
My branch to fix all of these things is called: "fixup-master-3"

**Comment by FuadBalashov** [comment]
thanks for doing the investigation. Let's just include it in the starter app then and consider adding a comment so noone else  wonders why we did this.

**Comment by FuadBalashov** [comment]
@ben-edgar lmk when its ready to review

**Comment by ben-edgar** [comment]
I'll try to do some more at lunch today.

**Comment by ben-edgar** [comment]
@FuadBalashov @n-kumari please review the branch fixup-master-3!!!! I found some extra time this morning.

https://github.com/ben-edgar/meme-creator/tree/fixup-master-3

@lcc8we @megantracy93 FYI/for review. These are some updates we wanted to make!

**Comment by FuadBalashov** [comment]
Looks good, just one comment about setting the ref

**Comment by ben-edgar** [comment]
Resolved all issues I will update the snacks for each commit and then close this issue! (and overwrite master :)

**Comment by n-kumari** [comment]
Thanks @ben-edgar

**Comment by ben-edgar** [comment]
All links to snacks and commits on our presentation has been updated! Closing.
